# Generated by Django 3.2 on 2021-04-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, max_length=200, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=200, null=True)),
                ('job_function', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('industries', models.CharField(blank=True, max_length=200, null=True)),
                ('processed', models.BooleanField(default=False))
            ],
        ),
    ]
