# Generated by Django 3.2 on 2021-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='query',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
